---
title: "iteration and listcols"
author: "Yuqi Miao"
date: "10/29/2019"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r}
library(tidyverse)

set.seed(1)
```

```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))
l ## broad collection of all kind of stuff
```

```{r}
l$mat
l[[2]] ### use [[]] !

mean(l$vec_numeric)
```


```{r}
df = tibble(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

is.list(df)  ## tibble creates lists
### use [[]] to subset number index of df!!
```



```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```


# loop

```{r}

output = vector("list", length = 4) ### 创建空集

for (i in 1:4) {
  output[[i]] = mean_and_sd(df[[i]])
}
```

### or just

```{r}
output <- map(df,mean_and_sd)
```

# map variant

```{r}

## map varient change the output class

output = map(df, median) 
output_median = map_dbl(df,median)
output_ms = map_df(df,mean_and_sd)

output_ms = map_df(.x = df, ~mean_and_sd(.x)) ## ~ everything, .x is the placeholder.

## output = map2(.x = input_1, .y = input_2, ~func(arg_1 = .x, arg_2 = .y)) 多个变量！
```



```{r}
library(rvest)

read_page_reviews = function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  data_frame(title, stars, text)
}
```


```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

output=vector("list", length = 5)
for (i in 1:5) {
    output[[i]] = read_page_reviews(vec_urls[i])
    
}

output = map(vec_urls,read_page_reviews)
```



# list columns

```{r, message=F}
weather = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2016-01-01",
    date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## nest within station

```{r}
weather_nest = 
  nest(weather, data = date:tmin) ## 说明那些数据是要保留的，剩下的是分类变量

weather_nest ## list of dataframes of same attributes, 按照observation的类型分组.
```

```{r}
weather_nest %>% pull(data)
weather_nest$data[[1]]

weather_nest %>% unnest()
```



# operations on a list columns


```{r}
central_park_df <- weather_nest$data[[1]]


lm(tmax~tmin,data = central_park_df)


weather_lm <- function(df){
    lm(tmax~tmin,data = df)
}
## extract as a function <=> write a dedicated function


output = vector("list", length = 3)
for (i in 1:3) {
   output[[i]] = weather_lm(weather_nest$data[[i]])
}

output = map(weather_nest$data, weather_lm)

```



## integrate: 直接在df中使用函数

```{r}
weather_nest %>% 
    mutate(lin_models = map(data,weather_lm))
```


# example 1: Revisit napolean

```{r}
napolran = 
    tibble(
        page= 1:5,
        urls =str_c(url_base,page)
    ) %>% 
    mutate(reviews = map(urls, read_page_reviews)) %>% 
    unnest() %>% 
    select(-urls)
    
    
```



# example 2: read excel data in chunks

```{r}
# lotr_cell_ranges = 
#   tibble(
#     movie = c("fellowship_ring", "two_towers", "return_king"),
#     cells = c("B3:D6", "F3:H6", "J3:L6")
#   )
# lotr_tidy = 
#   lotr_cell_ranges %>% 
#   mutate(
#     word_data = map(cells, ~readxl::read_excel("./data/LotR_Words.xlsx", # range = .x))
#   ) %>% 
#   unnest(cols = word_data) %>% 
#   janitor::clean_names() %>% 
#   pivot_longer(
#     female:male,
#     names_to = "sex",
#     values_to = "words") %>%
#   mutate(race = str_to_lower(race)) %>% 
#   select(movie, everything(), -cells) 

```

