---
title: "iteration"
author: "Yuqi Miao"
date: "10/24/2019"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r}
library(tidyverse)
library(rvest)
set.seed(1)
```


# writing functions

## get started

```{r}
x <-  rnorm(30,4,2.3)
z_trans <- (x-mean(x))/sd(x)
x2 <-  rnorm(30,6,0.4)

```

### fuction

```{r}
z_score <- function(x) {
   (x-mean(x))/sd(x)
}

z2_trans <- z_score(x2)
```

### try out

```{r}
# z_score(sample(c(TRUE, FALSE), 25, replace = TRUE))
# z_score(3)

## This can also used to debug the function
z_score <- function(x){
  if(!as.numeric(x)){
    stop("x should be a number")
  }else if(length(x)<3){
    stop("x should be longer than 3")
  }
  (x-mean(x))/sd(x)
}
z_score(rnorm(10))
```


# Multiple outputs

* **By using a list or a tibble to contain all outputs in this function, we can get multiple outputs by using [[]] to index the final list**

```{r}
mean_and_sd <- function(input_x){
    if(!is.numeric(x)){
        stop("x should be numeric")
    }else if(length(x)<3){
        stop("x should be longer than 3")
    }

    list(
        mean_input = mean(input_x),
        sd = sd(input_x),
        z_score = (input_x-mean(input_x))/sd(input_x)
    )
}

mean_and_sd = function(x){
  if(!is.numeric(x)){
    stop("x should be numeric")
  }else if(length(x)<2){
    stop("length of x should be longer than 1")
  }
  mean = mean(x)
  sd = sd(x)
  tibble(
    mean = mean, ## in essential, tibble is also a list
    sd = sd
  )
}
set.seed(1)
mean_and_sd(rnorm(10))[[1]]
```

# multiple input

```{r}
sim_data = tibble(
  x = rnorm(10,3,3),
  y = 3 + 10*x + rnorm(10,0,2)
)
ls_fit = lm(y~x, data = sim_data)

sim_reg = function(n, beta0 = 3, beta1 = 10){
  sim_data = tibble(
    x = rnorm(n,3,3),
    y = beta0 + beta1*x + rnorm(n,0,1)
  )
  ls_fit = lm(y~x, data = sim_data)
  coef(ls_fit)
}

sim_reg(300,1,2)
```



## quick example

unsuccessful case, for the url cannot be scraping, why?

```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  review_text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}

url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)
dynamite_reviews <- vector("list", length = 5)
for (i in 1:5) {
  dynamite_reviews[[i]] = read_page_reviews(vec_urls[i])
  
}
bind_rows(dynamite_reviews)
```


# Functions as arguments

```{r}
x = rnorm(25,0,1)
my_summary <- function(x, summ_func){
  summ_func(x)
}
my_summary(x,sum)
my_summary(x,mean)
```

# global and local

```{r}
f = function(x) {
  z = x + y 
  z
}
x = 1
y = 2
f(x = y)

## global var can be used in a fucntion, but it would be hard to track, so try not to use the same name!
a = 1
b = 2
f(x = a) # z = a+y
f(x = b) # z = b+y
```





